# Generated by Django 4.2.7 on 2024-04-27 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="course",
            name="lottieicon",
            field=models.ImageField(default="", upload_to="post/lottieicon"),
        ),
    ]
