# Generated by Django 4.2.7 on 2024-04-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_course_created_course_lottieicon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lottieicon",
            field=models.URLField(blank=True, null=True),
        ),
    ]
