# Generated by Django 4.2.7 on 2024-04-27 13:52

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_course_lottieicon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                default="Enter text here", verbose_name="Text"
            ),
        ),
    ]
