# Generated by Django 4.2.7 on 2024-05-05 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_tag_quiz_progress_enrollment_discussionpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="about",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
                ("created", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
