# Generated by Django 4.2.7 on 2024-05-11 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_prosemirrorcontent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProseMirrorContent",
        ),
    ]
