# Generated by Django 4.2.7 on 2024-05-11 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_remove_module_instructor_submodule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submodule",
            options={"verbose_name": "SubModule", "verbose_name_plural": "SubModules"},
        ),
        migrations.RenameField(
            model_name="submodule",
            old_name="submodule",
            new_name="module",
        ),
    ]
