# Generated by Django 4.2.7 on 2024-05-13 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_alter_submodule_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="description",
        ),
        migrations.RemoveField(
            model_name="module",
            name="description",
        ),
    ]
