# Generated by Django 4.2.7 on 2024-05-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_remove_lesson_description_remove_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="enrolled",
            field=models.BooleanField(default=False),
        ),
    ]
